### ISSUE TITLE
Does not support fork-repositories

### ISSUE THREAD

**Issue by LitoMore** [vadimdemedes/switch-branch-cli#7]
### How to reproduce

```shell
git clone git@github.com:LitoMore/switch-branch-cli.git
cd switch-branch-cli
npm i
npm run build
./dist/cli.js
```

Our `getBranches` logic only fetch PRs from the origin repository.

But for fork-repositories we should fetch PRs from the origin or upstream repository. Like this below:

<img width="1025" alt="CleanShot 2022-06-25 at 01 19 56@2x" src="https://user-images.githubusercontent.com/8186898/175610968-18b4dc51-74ea-473a-8391-70ace3277924.png">

We can refer to the [`gh`](https://github.com/cli/cli) to design our app.

**Comment by vadimdemedes** [comment]
I'm ok with it not supporting forked repositories. It's meant for switching the PRs you submit to the origin repository anyway.

Thanks for reporting the issue 👍
